- name: composer
  src: geerlingguy.composer
  version: 1.7.0

- name: ntp
  src: geerlingguy.ntp
  version: 1.6.0

- name: logrotate
  src: nickhammond.logrotate
  version: v0.0.5

- name: swapfile
  src: kamaln7.swapfile
  version: 4850d8a

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.3
