project_shared_children:
  - path: web/app/uploads
    src: uploads

# The project_environment is a list of environment variables that can be used in hooks
# Example:
# project_environment:
#   WP_ENV: "production"
project_environment:
  WP_ENV: "{{ env }}"

# Whether to run `wp core update-db` at end of each deploy
update_db_on_deploy: true
